export default {
	GET_CATEGORIES: Symbol("GET_CATEGORIES"),
	RESOLVE_GET_CATEGORIES: Symbol("RESOLVE_GET_CATEGORIES"),
	REJECT_GET_CATEGORIES: Symbol("REJECT_GET_CATEGORIES"),
	GET_PRODUCTS: Symbol("GET_PRODUCTS"),
	RESOLVE_GET_PRODUCTS: Symbol("RESOLVE_GET_PRODUCTS"),
	REJECT_GET_PRODUCTS: Symbol("REJECT_GET_PRODUCTS"),
	SELECT_CATEGORY: Symbol("SELECT_CATEGORY"),
	GET_CATEGORY_PRODUCTS: Symbol("GET_CATEGORY_PRODUCTS"),
	RESOLVE_GET_CATEGORY_PRODUCTS: Symbol("RESOLVE_GET_CATEGORY_PRODUCTS"),
	REJECT_GET_CATEGORY_PRODUCTS: Symbol("REJECT_GET_CATEGORY_PRODUCTS"),
	ADD_PRODUCT_TO_CATEGORY: Symbol("ADD_PRODUCT_TO_CATEGORY"),
	RESOLVE_ADD_PRODUCT_TO_CATEGORY: Symbol("RESOLVE_ADD_PRODUCT_TO_CATEGORY"),
	REJECT_ADD_PRODUCT_TO_CATEGORY: Symbol("REJECT_ADD_PRODUCT_TO_CATEGORY"),
	DELETE_PRODUCT_FROM_CATEGORY: Symbol("DELETE_PRODUCT_FROM_CATEGORY"),
	RESOLVE_DELETE_PRODUCT_FROM_CATEGORY: Symbol("RESOLVE_DELETE_PRODUCT_FROM_CATEGORY"),
	REJECT_DELETE_PRODUCT_FROM_CATEGORY: Symbol("REJECT_DELETE_PRODUCT_FROM_CATEGORY")
};