//import { ObjectID } from "mongodb";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = [
    { "Id": 1, "QuantityPerUnit": "10 boxes x 20 bags", "UnitPrice": 39, "CategoryId": 1, "Name": "Chai", "Discontinued": false },
    { "Id": 2, "QuantityPerUnit": "24 - 12 oz bottles", "UnitPrice": 19.0, "CategoryId": 1, "Name": "Chang", "Discontinued": true },
    { "Id": 3, "QuantityPerUnit": "12 - 550 ml bottles", "UnitPrice": 10.0, "CategoryId": 6, "Name": "Aniseed Syrup", "Discontinued": false },
    { "Id": 4, "QuantityPerUnit": "48 - 6 oz jars", "UnitPrice": 22.0, "CategoryId": 6, "Name": "Chef Anton`s Cajun Seasoning", "Discontinued": true },
    { "Id": 5, "QuantityPerUnit": "36 boxes", "UnitPrice": 21.35, "CategoryId": 6, "Name": "Chef Anton`s Gumbo Mix", "Discontinued": false },
    { "Id": 6, "QuantityPerUnit": "12 - 8 oz jars", "UnitPrice": 25.0, "CategoryId": 6, "Name": "Grandma`s Boysenberry Spread", "Discontinued": false },
    { "Id": 7, "QuantityPerUnit": "12 - 200 ml jars", "UnitPrice": 31.0, "CategoryId": 5, "Name": "Ikura", "Discontinued": false },
    { "Id": 8, "QuantityPerUnit": "1 kg pkg.", "UnitPrice": 21.0, "CategoryId": 7, "Name": "Queso Cabrales", "Discontinued": false },
    { "Id": 9, "QuantityPerUnit": "10 - 500 g pkgs.", "UnitPrice": 38.0, "CategoryId": 7, "Name": "Queso Manchego La Pastora", "Discontinued": true },
    { "Id": 10, "QuantityPerUnit": "2 kg box", "UnitPrice": 6.0, "CategoryId": 5, "Name": "Konbu", "Discontinued": false },
    { "Id": 11, "QuantityPerUnit": "40 - 100 g pkgs.", "UnitPrice": 23.25, "CategoryId": 4, "Name": "Tofu", "Discontinued": false },
    { "Id": 12, "QuantityPerUnit": "24 - 250 ml bottles", "UnitPrice": 15.5, "CategoryId": 6, "Name": "Genen Shouyu", "Discontinued": false },
    { "Id": 13, "QuantityPerUnit": "32 - 500 g boxes", "UnitPrice": 17.45, "CategoryId": 8, "Name": "Pavlova", "Discontinued": false },
    { "Id": 14, "QuantityPerUnit": "20 - 1 kg tins", "UnitPrice": 39.0, "CategoryId": 3, "Name": "Alice Mutton", "Discontinued": false },
    { "Id": 15, "QuantityPerUnit": "16 kg pkg.", "UnitPrice": 62.5, "CategoryId": 5, "Name": "Carnarvon Tigers", "Discontinued": false },
    { "Id": 16, "QuantityPerUnit": "10 boxes x 12 pieces", "UnitPrice": 9.2, "CategoryId": 8, "Name": "Teatime Chocolate Biscuits", "Discontinued": true },
    { "Id": 17, "QuantityPerUnit": "30 gift boxes", "UnitPrice": 81.0, "CategoryId": 8, "Name": "Sir Rodney`s Marmalade", "Discontinued": false },
    { "Id": 18, "QuantityPerUnit": "24 pkgs. x 4 pieces", "UnitPrice": 10.0, "CategoryId": 8, "Name": "Sir Rodney`s Scones", "Discontinued": false },
    { "Id": 19, "QuantityPerUnit": "12 - 1 lb pkgs.", "UnitPrice": 30.0, "CategoryId": 4, "Name": "Uncle Bob`s Organic Dried Pears", "Discontinued": true },
    { "Id": 20, "QuantityPerUnit": "12 - 12 oz jars", "UnitPrice": 40.0, "CategoryId": 6, "Name": "Northwoods Cranberry Sauce", "Discontinued": false },
    { "Id": 21, "QuantityPerUnit": "18 - 500 g pkgs.", "UnitPrice": 97.0, "CategoryId": 3, "Name": "Mishi Kobe Niku", "Discontinued": false },
    { "Id": 22, "QuantityPerUnit": "24 - 500 g pkgs.", "UnitPrice": 21.0, "CategoryId": 2, "Name": "Gustaf`s Knäckebröd", "Discontinued": false },
    { "Id": 23, "QuantityPerUnit": "12 - 250 g pkgs.", "UnitPrice": 9.0, "CategoryId": 2, "Name": "Tunnbröd", "Discontinued": false },
    { "Id": 24, "QuantityPerUnit": "12 - 355 ml cans", "UnitPrice": 4.5, "CategoryId": 1, "Name": "Guaraná Fantástica", "Discontinued": false },
    { "Id": 25, "QuantityPerUnit": "20 - 450 g glasses", "UnitPrice": 14.0, "CategoryId": 8, "Name": "NuNuCa Nuß-Nougat-Creme", "Discontinued": true },
    { "Id": 26, "QuantityPerUnit": "100 - 250 g bags", "UnitPrice": 31.23, "CategoryId": 8, "Name": "Gumbär Gummibärchen", "Discontinued": false },
    { "Id": 27, "QuantityPerUnit": "10 - 200 g glasses", "UnitPrice": 25.89, "CategoryId": 5, "Name": "Nord-Ost Matjeshering", "Discontinued": true },
    { "Id": 28, "QuantityPerUnit": "12 - 100 g pkgs", "UnitPrice": 12.5, "CategoryId": 7, "Name": "Gorgonzola Telino", "Discontinued": false },
    { "Id": 29, "QuantityPerUnit": "24 - 200 g pkgs.", "UnitPrice": 32.0, "CategoryId": 7, "Name": "Mascarpone Fabioli", "Discontinued": false },
    { "Id": 30, "QuantityPerUnit": "500 g", "UnitPrice": 2.5, "CategoryId": 7, "Name": "Geitost", "Discontinued": false },
    { "Id": 31, "QuantityPerUnit": "24 - 12 oz bottles", "UnitPrice": 14.0, "CategoryId": 1, "Name": "Sasquatch Ale", "Discontinued": false },
    { "Id": 32, "QuantityPerUnit": "24 - 12 oz bottles", "UnitPrice": 18.0, "CategoryId": 1, "Name": "Steeleye Stout", "Discontinued": false },
    { "Id": 33, "QuantityPerUnit": "24 - 250 g  jars", "UnitPrice": 19.0, "CategoryId": 5, "Name": "Inlagd Sill", "Discontinued": false },
    { "Id": 34, "QuantityPerUnit": "12 - 500 g pkgs.", "UnitPrice": 26.0, "CategoryId": 5, "Name": "Gravad lax", "Discontinued": false },
    { "Id": 35, "QuantityPerUnit": "12 - 75 cl bottles", "UnitPrice": 263.5, "CategoryId": 1, "Name": "Côte de Blaye", "Discontinued": false },
    { "Id": 36, "QuantityPerUnit": "750 cc per bottle", "UnitPrice": 18.0, "CategoryId": 1, "Name": "Chartreuse verte", "Discontinued": false },
    { "Id": 37, "QuantityPerUnit": "24 - 4 oz tins", "UnitPrice": 18.4, "CategoryId": 5, "Name": "Boston Crab Meat", "Discontinued": false },
    { "Id": 38, "QuantityPerUnit": "12 - 12 oz cans", "UnitPrice": 9.65, "CategoryId": 5, "Name": "Jack`s New England Clam Chowder", "Discontinued": true },
    { "Id": 39, "QuantityPerUnit": "32 - 1 kg pkgs.", "UnitPrice": 14.0, "CategoryId": 2, "Name": "Singaporean Hokkien Fried Mee", "Discontinued": true },
    { "Id": 40, "QuantityPerUnit": "16 - 500 g tins", "UnitPrice": 46.0, "CategoryId": 1, "Name": "Ipoh Coffee", "Discontinued": false },
    { "Id": 41, "QuantityPerUnit": "1k pkg.", "UnitPrice": 9.5, "CategoryId": 5, "Name": "Rogede sild", "Discontinued": false },
    { "Id": 42, "QuantityPerUnit": "4 - 450 g glasses", "UnitPrice": 12.0, "CategoryId": 5, "Name": "Spegesild", "Discontinued": false },
    { "Id": 43, "QuantityPerUnit": "10 - 4 oz boxes", "UnitPrice": 9.5, "CategoryId": 8, "Name": "Zaanse koeken", "Discontinued": false },
    { "Id": 44, "QuantityPerUnit": "100 - 100 g pieces", "UnitPrice": 43.9, "CategoryId": 8, "Name": "Schoggi Schokolade", "Discontinued": false },
    { "Id": 45, "QuantityPerUnit": "25 - 825 g cans", "UnitPrice": 45.6, "CategoryId": 4, "Name": "Rössle Sauerkraut", "Discontinued": false },
    { "Id": 46, "QuantityPerUnit": "50 bags x 30 sausgs.", "UnitPrice": 123.79, "CategoryId": 3, "Name": "Thüringer Rostbratwurst", "Discontinued": true },
    { "Id": 47, "QuantityPerUnit": "10 pkgs.", "UnitPrice": 12.75, "CategoryId": 8, "Name": "Chocolade", "Discontinued": false },
    { "Id": 48, "QuantityPerUnit": "24 - 50 g pkgs.", "UnitPrice": 20.0, "CategoryId": 8, "Name": "Maxilaku", "Discontinued": false },
    { "Id": 49, "QuantityPerUnit": "12 - 100 g bars", "UnitPrice": 16.25, "CategoryId": 8, "Name": "Valkoinen suklaa", "Discontinued": true },
    { "Id": 50, "QuantityPerUnit": "50 - 300 g pkgs.", "UnitPrice": 53.0, "CategoryId": 4, "Name": "Manjimup Dried Apples", "Discontinued": true },
    { "Id": 51, "QuantityPerUnit": "16 - 2 kg boxes", "UnitPrice": 7.0, "CategoryId": 2, "Name": "Filo Mix", "Discontinued": false },
    { "Id": 52, "QuantityPerUnit": "24 - 250 g pkgs.", "UnitPrice": 38.0, "CategoryId": 2, "Name": "Gnocchi di nonna Alice", "Discontinued": true },
    { "Id": 53, "QuantityPerUnit": "24 - 250 g pkgs.", "UnitPrice": 19.5, "CategoryId": 2, "Name": "Ravioli Angelo", "Discontinued": false },
    { "Id": 54, "QuantityPerUnit": "24 pieces", "UnitPrice": 13.25, "CategoryId": 5, "Name": "Escargots de Bourgogne", "Discontinued": false },
    { "Id": 55, "QuantityPerUnit": "5 kg pkg.", "UnitPrice": 55.0, "CategoryId": 7, "Name": "Raclette Courdavault", "Discontinued": false },
    { "Id": 56, "QuantityPerUnit": "15 - 300 g rounds", "UnitPrice": 34.0, "CategoryId": 7, "Name": "Camembert Pierrot", "Discontinued": true },
    { "Id": 57, "QuantityPerUnit": "24 - 500 ml bottles", "UnitPrice": 28.5, "CategoryId": 6, "Name": "Sirop d`érable", "Discontinued": true },
    { "Id": 58, "QuantityPerUnit": "48 pies", "UnitPrice": 49.3, "CategoryId": 8, "Name": "Tarte au sucre", "Discontinued": false },
    { "Id": 59, "QuantityPerUnit": "15 - 625 g jars", "UnitPrice": 43.9, "CategoryId": 6, "Name": "Vegie-spread", "Discontinued": false },
    { "Id": 60, "QuantityPerUnit": "20 bags x 4 pieces", "UnitPrice": 33.25, "CategoryId": 2, "Name": "Wimmers gute Semmelknödel", "Discontinued": true },
    { "Id": 61, "QuantityPerUnit": "32 - 8 oz bottles", "UnitPrice": 21.05, "CategoryId": 6, "Name": "Louisiana Fiery Hot Pepper Sauce", "Discontinued": true },
    { "Id": 62, "QuantityPerUnit": "24 - 8 oz jars", "UnitPrice": 17.0, "CategoryId": 6, "Name": "Louisiana Hot Spiced Okra", "Discontinued": false },
    { "Id": 63, "QuantityPerUnit": "24 - 12 oz bottles", "UnitPrice": 14.0, "CategoryId": 1, "Name": "Laughing Lumberjack Lager", "Discontinued": true },
    { "Id": 64, "QuantityPerUnit": "10 boxes x 8 pieces", "UnitPrice": 12.5, "CategoryId": 8, "Name": "Scottish Longbreads", "Discontinued": false },
    { "Id": 65, "QuantityPerUnit": "Crate", "UnitPrice": 666, "CategoryId": 7, "Name": "MyProduct", "Discontinued": true },
    { "Id": 66, "QuantityPerUnit": "24 - 355 ml bottles", "UnitPrice": 15.0, "CategoryId": 1, "Name": "Outback Lager", "Discontinued": false },
    { "Id": 67, "QuantityPerUnit": "10 - 500 g pkgs.", "UnitPrice": 21.5, "CategoryId": 7, "Name": "Flotemysost", "Discontinued": false },
    { "Id": 68, "QuantityPerUnit": "24 - 200 g pkgs.", "UnitPrice": 34.8, "CategoryId": 7, "Name": "Mozzarella di Giovanni", "Discontinued": false },
    { "Id": 69, "QuantityPerUnit": "24 - 150 g jars", "UnitPrice": 15.0, "CategoryId": 5, "Name": "Röd Kaviar", "Discontinued": false },
    { "Id": 70, "QuantityPerUnit": "48 pieces", "UnitPrice": 32.8, "CategoryId": 3, "Name": "Perth Pasties", "Discontinued": true },
    { "Id": 71, "QuantityPerUnit": "16 pies", "UnitPrice": 7.45, "CategoryId": 3, "Name": "Tourtière", "Discontinued": true },
    { "Id": 72, "QuantityPerUnit": "24 boxes x 2 pies", "UnitPrice": 24.0, "CategoryId": 3, "Name": "Pâté chinois", "Discontinued": true },
    { "Id": 73, "QuantityPerUnit": "5 kg pkg.", "UnitPrice": 10.0, "CategoryId": 4, "Name": "Longlife Tofu", "Discontinued": false },
    { "Id": 74, "QuantityPerUnit": "24 - 0.5 l bottles", "UnitPrice": 7.75, "CategoryId": 1, "Name": "Rhönbräu Klosterbier", "Discontinued": true },
    { "Id": 75, "QuantityPerUnit": "500 ml", "UnitPrice": 18.0, "CategoryId": 1, "Name": "Lakkalikööri", "Discontinued": false },
    { "Id": 76, "QuantityPerUnit": "12 boxes", "UnitPrice": 13.0, "CategoryId": 6, "Name": "Original Frankfurter grüne Soße", "Discontinued": false } //'"578f2b8c12eaebabec4af288"'=>76 //'"578f2baa12eaebabec4af28e"'->6
];
//# sourceMappingURL=products.js.map